//! The MixMap's lookup tables and integer conversions (spec `audio-specs/mixmap-spec.md` §5.0).
//!
//! Every table is generated by its formula. Against the TU3 image (`mxb_tool.py tables`) POW, LOG,
//! CURVE and SEMI are identical; FINE differs by one ulp at entries 15, 36, 56 and 65, which are
//! patched here with the image's values (facts, not code).

pub const SILENT_MB: i32 = -10_000;

#[derive(Clone, Debug)]
pub struct Tables {
    /// `int(32768·10^(−(r+1)/2000))`, r = 0..601, with POW[601] = 16384.
    pub pow: [i32; 602],
    /// lin → mB fraction table (512 entries).
    pub log: [i32; 512],
    /// `floor(32767·cos(π/2·i/511))`, i = 0..511.
    pub curve: [i32; 512],
    /// f32(2^(i/12)).
    pub semi: [f32; 12],
    /// f32(2^(i/1200)), four entries patched.
    pub fine: [f32; 100],
    /// Cents per mB for ratios > 1 and ≤ 1 (`0x822F8AE0` / `0x822F8AE4`).
    pub k_ratio: (f32, f32),
    /// The envelopes' "too short to ramp" threshold (ms, `0x822F8ADC`).
    pub k_min_ramp: f32,
    /// One 60 Hz frame in ms (`0x822F8F04`).
    pub k_frame_ms: f32,
}

impl Default for Tables {
    fn default() -> Self {
        Self::generate()
    }
}

impl Tables {
    pub fn generate() -> Self {
        let mut pow = [0i32; 602];
        for (r, p) in pow.iter_mut().enumerate() {
            *p = (32768.0 * 10f64.powf(-((r + 1) as f64) / 2000.0)) as i32;
        }
        pow[601] = 16384;
        let mut log = [0i32; 512];
        for (i, l) in log.iter_mut().enumerate() {
            let above = pow.iter().filter(|&&p| p >= 16384 + 32 * i as i32).count() as i32;
            *l = (601 - above).max(0);
        }
        let mut curve = [0i32; 512];
        for (i, c) in curve.iter_mut().enumerate() {
            *c = (32767.0 * (std::f64::consts::FRAC_PI_2 * i as f64 / 511.0).cos()).floor() as i32;
        }
        let semi = std::array::from_fn(|i| 2f64.powf(i as f64 / 12.0) as f32);
        let mut fine: [f32; 100] = std::array::from_fn(|i| 2f64.powf(i as f64 / 1200.0) as f32);
        fine[15] = 1.008_701_920_509_338_4;
        fine[36] = 1.021_012_187_004_089_4;
        fine[56] = 1.032_875_776_290_893_6;
        fine[65] = 1.038_259_267_807_006_8;
        Self {
            pow,
            log,
            curve,
            semi,
            fine,
            // ±1200/602.06 as stored in the image (not the nearest f32 to 1.99316).
            k_ratio: (f32::from_bits(0xBFFF_1FC4), f32::from_bits(0x3FFF_1FC4)),
            k_min_ramp: 16.666,
            // 16.66667 as stored (2 ulps above the nearest f32 to 1000/60).
            k_frame_ms: f32::from_bits(0x4185_5557),
        }
    }

    /// mB → Q15 linear, for m ≤ 0 (anything above 0 gives 0, as retail's callers never pass it).
    /// 0 mB → 32730, not 32767.
    pub fn mb_to_lin(&self, m: i32) -> i32 {
        if m > 0 {
            return 0;
        }
        let neg = -(m as i64);
        let k = neg / 602;
        let rem = neg - 602 * k;
        if k > 15 {
            return 0;
        }
        self.pow[rem as usize] >> k
    }

    /// Q15 linear → mB; 0 or anything above 32767 (as an unsigned word) → `default`.
    pub fn lin_to_mb_or(&self, x: i32, default: i32) -> i32 {
        let x = x as u32;
        if x == 0 || x > 0x7FFF {
            return default;
        }
        let c = 14 - (31 - x.leading_zeros()) as i32; // 0 for 16384..32767
        let idx = if c <= 5 {
            ((x - (1 << (14 - c))) >> (5 - c)) as usize
        } else {
            let scaled = (x << (c - 5)).wrapping_sub(512) | ((1 << (c - 5)) - 1);
            (scaled & 0x1FF) as usize
        };
        self.log[idx] - 602 * (c + 1)
    }

    pub fn lin_to_mb(&self, x: i32) -> i32 {
        self.lin_to_mb_or(x, SILENT_MB)
    }

    /// The input curve `kind` (0..9) applied to a Q15 value (spec §5.0 `shape`).
    pub fn shape(&self, x: i32, kind: u32) -> i32 {
        let frac = |x: i32| (((x >> 1) & 0xF) << 10) | 1023;
        match kind {
            0 => {
                let i = x >> 6;
                if !(0..511).contains(&i) {
                    return 0;
                }
                let t = self.curve[i as usize];
                if t == 0 {
                    return 0;
                }
                ((self.curve[i as usize + 1] - t).wrapping_mul(frac(x)) >> 15).wrapping_add(t)
            }
            1 => self.shape(32767i32.wrapping_sub(x), 0),
            2 => {
                let y = self.shape(x, 0);
                y.wrapping_mul(y) >> 15
            }
            3 => self.shape(32767i32.wrapping_sub(x), 2),
            4 => {
                let i = 511i32.wrapping_sub(x >> 6);
                let at = |i: i32| if (0..512).contains(&i) { Some(self.curve[i as usize]) } else { None };
                let a = at(i).map_or(32767, |c| 32767 - c);
                let b = 32767 - at(i.wrapping_add(1)).unwrap_or(0);
                ((b - a).wrapping_mul(frac(x)) >> 15).wrapping_add(a)
            }
            5 => self.shape(32767i32.wrapping_sub(x), 4),
            6 => {
                let y = self.shape(x, 4);
                y.wrapping_mul(y) >> 15
            }
            7 => self.shape(32767i32.wrapping_sub(x), 6),
            8 => 32767i32.wrapping_sub(x),
            9 => x,
            _ => 0,
        }
    }

    /// `shape(trunc(f·32767), kind) / 32767` in f32 (the envelopes' curve on a 0..1 progress).
    pub fn curve01(&self, kind: u32, f: f32) -> f32 {
        let r = if kind <= 9 { self.shape(trunc(f * 32767.0), kind) } else { 0 };
        r as f32 * (1.0f32 / 32767.0)
    }

    /// 2^(c/1200) from whole octaves × SEMI × FINE, single precision (spec §5.0).
    pub fn cents_ratio(&self, c: i32) -> f32 {
        let neg = c < 0;
        let mut c = c;
        let mut f0 = 1.0f32;
        if c >= 1200 {
            let q = c / 1200;
            c -= q * 1200;
            f0 *= 2f32.powi(q);
        }
        if c <= -1200 {
            let q = (-1200 - c) / 1200 + 1;
            c += q * 1200;
            f0 *= 2f32.powi(q);
        }
        if !neg {
            return (self.fine[(c % 100) as usize] * self.semi[(c / 100) as usize]) * f0;
        }
        let r = -c;
        ((1.0f32 / self.semi[(r / 100) as usize]) / f0) * (1.0f32 / self.fine[(r % 100) as usize])
    }

    /// Ratio → cents via the mB table (the Doppler target).
    pub fn ratio_to_cents(&self, r: f32) -> i32 {
        let (lin, k) = if r > 1.0 { (32767.0f32 / r, self.k_ratio.0) } else { (r * 32767.0, self.k_ratio.1) };
        trunc(self.lin_to_mb(trunc(lin)) as f32 * k)
    }

    /// Owner reader vfunc56: cents → pitch with 4096 = 1.0.
    pub fn pitch_4096(&self, cents: i32) -> i32 {
        trunc(self.cents_ratio(cents) * 4096.0)
    }
}

/// Round toward zero (fctiwz); NaN → 0, saturating.
pub fn trunc(x: f32) -> i32 {
    if x.is_nan() { 0 } else { x as i32 }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spec_examples() {
        let t = Tables::generate();
        assert_eq!(t.mb_to_lin(0), 32730);
        assert_eq!(t.mb_to_lin(-10000), 0);
        assert_eq!(t.mb_to_lin(-602), 32730 >> 1);
        assert_eq!(t.lin_to_mb(32767), -1);
        assert_eq!(t.lin_to_mb(16384), -602);
        assert_eq!(t.lin_to_mb(1), 601 - 602 * 15);
        assert_eq!(t.lin_to_mb(0), -10000);
        assert_eq!(t.lin_to_mb(40000), -10000);
        assert_eq!(t.pow[601], 16384);
        assert_eq!(t.curve[0], 32767);
        assert_eq!(t.curve[511], 0);
        // Curves: cos falls 1 → 0, sin rises, 1−x, x.
        assert_eq!(t.shape(0, 0), 32766); // the 4-bit fraction interpolates a little
        assert_eq!(t.shape(32767, 0), 0);
        assert_eq!(t.shape(0, 1), 0);
        assert_eq!(t.shape(1000, 8), 31767);
        assert_eq!(t.shape(1000, 9), 1000);
        assert_eq!(t.shape(1000, 12), 0);
        // Pitch reader: 0 cents = 4096, an octave up/down.
        assert_eq!(t.pitch_4096(0), 4096);
        assert_eq!(t.pitch_4096(1200), 8192);
        assert_eq!(t.pitch_4096(-1200), 2048);
        // Filter conversion: −2 cents of 25 kHz = 24971 Hz, −10000 → 77 Hz.
        assert_eq!(trunc(t.cents_ratio(-2) * 25000.0), 24971);
        assert_eq!(trunc(t.cents_ratio(-1) * 25000.0), 24985);
        assert_eq!(trunc(t.cents_ratio(-10000) * 25000.0), 77);
    }

    /// The generated tables against the retail image's, when the private TU3 image is present
    /// (`SKATE_TU3_IMAGE` = the dumped `default_82000000_011B0000.bin`).
    #[test]
    #[ignore = "needs the private install data"]
    fn tables_match_the_image_when_present() {
        let Some(path) = std::env::var_os("SKATE_TU3_IMAGE").filter(|v| !v.is_empty()) else {
            panic!("missing private data: SKATE_TU3_IMAGE (the TU3 image) is not set");
        };
        let path = std::path::PathBuf::from(path);
        let Ok(img) = std::fs::read(&path) else {
            panic!("missing private data: no TU3 image at {}", path.display());
        };
        let word = |a: u32| u32::from_be_bytes(img[(a - 0x8200_0000) as usize..][..4].try_into().unwrap());
        let t = Tables::generate();
        for i in 0..512 {
            assert_eq!(t.log[i], word(0x82FD_BFB0 + 4 * i as u32) as i32, "log {i}");
            assert_eq!(t.curve[i], word(0x82FD_C7B0 + 4 * i as u32) as i32, "curve {i}");
        }
        for r in 0..602 {
            assert_eq!(t.pow[r], word(0x82FD_BFAC - 4 * r as u32) as i32, "pow {r}");
        }
        for i in 0..12 {
            assert_eq!(t.semi[i].to_bits(), word(0x82FD_CFB4 + 4 * i as u32), "semi {i}");
        }
        for i in 0..100 {
            assert_eq!(t.fine[i].to_bits(), word(0x82FD_CFE8 + 4 * i as u32), "fine {i}");
        }
        assert_eq!(t.k_ratio.0.to_bits(), word(0x822F_8AE0));
        assert_eq!(t.k_ratio.1.to_bits(), word(0x822F_8AE4));
        assert_eq!(t.k_min_ramp.to_bits(), word(0x822F_8ADC));
        assert_eq!(t.k_frame_ms.to_bits(), word(0x822F_8F04));
    }
}
