//! Native audio bridge hold-latch/clock vectors, not expected values generated by this port.
use skate_audio::player::bridge::OffboardHold;
#[test]
#[ignore = "requires SKATE_RETAIL_OFFBOARD_VECTORS from TU3 bridge824B0DA8"]
fn offboard_hold_matches_native_instruction_execution() {
 let text = std::fs::read_to_string(std::env::var_os("SKATE_RETAIL_OFFBOARD_VECTORS").expect("native hold vectors")).unwrap();
 assert!(text.starts_with("# TU3 offboard 824B0DA8;"));
 let hex = |s| u32::from_str_radix(s,16).unwrap();
 let mut state = OffboardHold::default();
 let mut count = 0;
 for (tick,line) in text.lines().filter(|l| !l.starts_with('#')).enumerate() {
  let v:Vec<_> = line.split_whitespace().collect();assert_eq!(v.len(),7);
  let expired=state.tick(v[0]=="1",f32::from_bits(hex(v[1])),f32::from_bits(hex(v[2])));
  assert_eq!(expired,v[3]=="1","expiry tick {tick}");
  assert_eq!(state.latched,v[4]=="1","latch tick {tick}");
  assert_eq!(state.clock.to_bits(),hex(v[5]),"clock tick {tick}");
  assert_eq!(state.start.to_bits(),hex(v[6]),"start tick {tick}");count+=1;
 }
 assert_eq!(count,4096);
}
