local MC = { loading = {} }
SKATEGM_MAPCHECK = MC

function MC.Generated(map)
	return tostring(map or ""):match("^sgm_skate3_") ~= nil
end

function MC.Message(name, map, reason)
	reason = tostring(reason or ""):lower()
	local who = name ~= "" and name or "Someone"
	local fix = "Everyone needs the same SkateGM version, with " .. map .. " generated by that version (installer > Generate maps)."
	if reason:find("differ", 1, true) then
		return who .. " couldn't join: their copy of " .. map .. " isn't the same as this server's. " .. fix
	end
	return who .. " left while loading. If Garry's Mod told them their map differs from the server's: " .. fix
end

function MC.Connected(userid) MC.loading[userid] = true end
function MC.Spawned(userid) MC.loading[userid] = nil end

function MC.Disconnected(data, map)
	local userid = data.userid
	local wasLoading = MC.loading[userid]
	MC.loading[userid] = nil
	if not wasLoading or tonumber(data.bot) == 1 or not MC.Generated(map) then return nil end
	return MC.Message(data.name or "", map, data.reason)
end

if gameevent and gameevent.Listen then
	gameevent.Listen("player_connect")
	gameevent.Listen("player_disconnect")
	hook.Add("player_connect", "skategm_mapcheck", function(data) MC.Connected(data.userid) end)
	hook.Add("PlayerInitialSpawn", "skategm_mapcheck", function(ply) MC.Spawned(ply:UserID()) end)
	hook.Add("player_disconnect", "skategm_mapcheck", function(data)
		local line = MC.Disconnected(data, game.GetMap())
		if not line then return end
		print("[SkateGM] " .. line)
		PrintMessage(HUD_PRINTTALK, "[SkateGM] " .. line)
	end)
end

return MC
